// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgWqF-djhYCuX8Ipf0lciOwDBhjoRK9o',
    appId: '1:260407059558:web:f975e3720decbb5b7c79a7',
    messagingSenderId: '260407059558',
    projectId: 'nl-discounts-dev',
    authDomain: 'nl-discounts-dev.firebaseapp.com',
    storageBucket: 'nl-discounts-dev.firebasestorage.app',
    measurementId: 'G-HCK9F765KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4pU6eDaFq4DFKw4M9LjnukBsq9ELZWk',
    appId: '1:260407059558:android:bbe68834becdd78b7c79a7',
    messagingSenderId: '260407059558',
    projectId: 'nl-discounts-dev',
    storageBucket: 'nl-discounts-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFUoXb1igHo-hWLrCD7zEUPFJJrDdbx0',
    appId: '1:260407059558:ios:7537d5e7142141c27c79a7',
    messagingSenderId: '260407059558',
    projectId: 'nl-discounts-dev',
    storageBucket: 'nl-discounts-dev.firebasestorage.app',
    iosClientId: '260407059558-a2q623tu5vl72q02vkmmp7c2f6o679j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nlDiscountsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHFUoXb1igHo-hWLrCD7zEUPFJJrDdbx0',
    appId: '1:260407059558:ios:7537d5e7142141c27c79a7',
    messagingSenderId: '260407059558',
    projectId: 'nl-discounts-dev',
    storageBucket: 'nl-discounts-dev.firebasestorage.app',
    iosClientId: '260407059558-a2q623tu5vl72q02vkmmp7c2f6o679j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nlDiscountsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgWqF-djhYCuX8Ipf0lciOwDBhjoRK9o',
    appId: '1:260407059558:web:6e25295f0ea7ffff7c79a7',
    messagingSenderId: '260407059558',
    projectId: 'nl-discounts-dev',
    authDomain: 'nl-discounts-dev.firebaseapp.com',
    storageBucket: 'nl-discounts-dev.firebasestorage.app',
    measurementId: 'G-201ZE96956',
  );

}