// lib/main.dart
import 'dart:io';
import 'dart:io' show Platform, File;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:image_picker/image_picker.dart';
import 'services/location_service.dart';
import 'package:geolocator/geolocator.dart'; // Needed for the Position type
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'providers/app_providers.dart';
import 'screens/watchlist_screen.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Skip Firebase initialization on Linux Desktop because the native plugin isn't supported.
  if (kIsWeb || !Platform.isLinux) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } else {
    print('⚠️ Running on Linux Desktop. Firebase initialization skipped.');
  }

  runApp( const ProviderScope(child: NederlandDiscountsApp()));
}

class NederlandDiscountsApp extends StatelessWidget {
  const NederlandDiscountsApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NL Discounts',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blueAccent),
        useMaterial3: true,
      ),
      home: const MainDashboard(),
    );
  }
}

class MainDashboard extends ConsumerStatefulWidget {
  const MainDashboard({super.key});

  @override
  ConsumerState<MainDashboard> createState() => _MainDashboardState();
}

class _MainDashboardState extends ConsumerState<MainDashboard> {

  @override
  void initState() {
    super.initState();
    // Fire and forget the notification handshake
    NotificationService().initializeAndSaveToken();
  }

  // We moved your camera logic here because the FAB lives on the Scaffold!
  Future<void> _takePhotoAndUpload(BuildContext context, WidgetRef ref) async {
    final locationAsync = ref.read(locationProvider);

    if (!locationAsync.hasValue) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Cannot upload: GPS location not found yet.')),
      );
      return;
    }

    final position = locationAsync.value!;
    final ImagePicker picker = ImagePicker();

    // 🛡️ The Linux Bypass
    ImageSource source = ImageSource.camera;
    if (!kIsWeb && Platform.isLinux) {
      print('💻 Linux detected. Opening File Explorer...');
      source = ImageSource.gallery;
    }

    final XFile? photo = await picker.pickImage(source: source);

    if (photo != null) {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => const Center(child: CircularProgressIndicator()),
      );

      try {
        File imageFile = File(photo.path);
        final apiService = ref.read(apiServiceProvider);

        final result = await apiService.uploadCrowdsourceDeal(
          1, position.latitude, position.longitude, imageFile
        );

        if (context.mounted) Navigator.pop(context); // Close dialog

        final aiData = result['deal_added'];
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('✅ AI Found: ${aiData['product_name']} at €${aiData['price']}!'),
              backgroundColor: Colors.green,
              duration: const Duration(seconds: 4),
            ),
          );
          ref.invalidate(discountsProvider);
        }
      } catch (e) {
        if (context.mounted) Navigator.pop(context);
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('❌ Upload failed: $e'), backgroundColor: Colors.red),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentIndex = ref.watch(navIndexProvider);

    // Our two screens
    final screens = [
      const LocalDealsView(), // Extracted deals list
      const WatchlistScreen(), // The new screen we built
    ];

    return Scaffold(
      appBar: AppBar(
        title: Text(currentIndex == 0 ? 'Local Deals' : 'My Watchlist'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        actions: [
          // We only show the refresh button on the deals tab
          if (currentIndex == 0)
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: () {
                ref.invalidate(locationProvider);
                ref.invalidate(discountsProvider);
              },
            )
        ],
      ),

      // The body changes based on the bottom nav index
      body: screens[currentIndex],

      // The Bottom Menu
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: currentIndex,
        onTap: (index) => ref.read(navIndexProvider.notifier).state = index,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.local_offer), label: 'Deals'),
          BottomNavigationBarItem(icon: Icon(Icons.list_alt), label: 'Watchlist'),
        ],
      ),

      // We only show the camera FAB when the user is on the Deals tab (Index 0)
      floatingActionButton: currentIndex == 0 ? FloatingActionButton.extended(
        onPressed: () => _takePhotoAndUpload(context, ref),
        icon: const Icon(Icons.camera_alt),
        label: const Text('Scan Deal'),
        backgroundColor: Colors.blueAccent,
      ) : null,
    );
  }
}

// ----------------------------------------------------------------------
// YOUR EXTRACTED DEALS VIEW (Just the list and location header)
// ----------------------------------------------------------------------
class LocalDealsView extends ConsumerWidget {
  const LocalDealsView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final discountsAsyncValue = ref.watch(discountsProvider);
    final locationAsyncValue = ref.watch(locationProvider);

    // Notice there is no Scaffold here anymore, just the Column!
    return discountsAsyncValue.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stackTrace) => Center(child: Text('🚨 Error: $error')),
      data: (deals) {
        return Column(
          children: [
            if (locationAsyncValue.value != null)
              Container(
                padding: const EdgeInsets.all(8.0),
                color: Colors.grey[200],
                width: double.infinity,
                child: Text('📍 Lat: ${locationAsyncValue.value!.latitude.toStringAsFixed(3)}, Lng: ${locationAsyncValue.value!.longitude.toStringAsFixed(3)}', textAlign: TextAlign.center),
              ),

            if (deals.isEmpty)
              const Expanded(child: Center(child: Text('No deals found within 15km.')))
            else
              Expanded(
                child: ListView.builder(
                  itemCount: deals.length,
                  itemBuilder: (context, index) {
                    final deal = deals[index];
                    return Card(
                      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                      child: ListTile(
                        leading: const Icon(Icons.local_offer, color: Colors.blue),
                        title: Text(deal['product'] ?? 'Unknown', style: const TextStyle(fontWeight: FontWeight.bold)),
                        subtitle: Text('${deal['supermarket']} • ${deal['distance_km']} km away'),
                        trailing: Text('€${deal['price']}', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.green)),
                      ),
                    );
                  },
                ),
              ),
          ],
        );
      }
    );
  }
}
